// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}

type PostRequest struct {
	Address string `json:"address"`
	Number  string `json:"number"`
}

type PostResponse struct {
	Address string `json:"address"`
	Number  string `json:"number"`
}
